### ISSUE TITLE
Explore alternative data structures

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/research#7]
**Tasks**:
- [x] [LazyTower](https://hackmd.io/@LCamel/LazyTower)
- [x] [MMR](https://neptune.cash/learn/mmr)
- [x] [Disjoint sets](https://en.wikipedia.org/wiki/Disjoint_sets)
- [x] [RSA accumulators](https://zkproof.org/2020/02/27/zkp-set-membership/)
- [x] [Indexed Merkle trees](https://docs.aztec.network/aztec/protocol/trees/indexed-merkle-tree)
